name: diplome_dima
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2

  auto_route: ^5.0.2
  flutter_datetime_picker: ^1.5.1
  firebase_auth: ^4.1.2
  firebase_core: ^2.2.0
  firebase_database: ^10.0.5
  firebase_storage: ^11.0.6
  fluttertoast: ^8.1.1
  http: ^0.13.5
  image_picker: ^0.8.6
  intl: ^0.17.0
  rxdart: ^0.27.3
  provider: ^6.0.4
  shared_preferences: ^2.0.15
  url_strategy: ^0.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.2
  auto_route_generator: ^5.0.3

flutter:
  uses-material-design: true

  assets:
    - assets/
